# Generated by Django 5.1.5 on 2025-02-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Us'},
        ),
    ]
