# Generated by Django 5.1.5 on 2025-02-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaboutus', '0002_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='sociallink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
    ]
